parameters:
  unchanged_files:
    - Par_AnnualEmissionLimit
    - Sets
    - Par_AnnualSectoralEmissionLimit
    - Par_BaseYearSlack
    - Par_CapacityFactor
    - Par_CapitalCostStorage
    - Par_EmissionActivityRatio
    - Par_EmissionContentPerFuel
    - Par_FixedCost
    - Par_InputActivityRatio
    - Par_MinStorageCharge
    - Par_ModelPeriodEmissionLimit
    - Par_ModelPeriodExogenousEmission
    - Par_OperationalLife
    - Par_OperationalLifeStorage
    - Par_ProductionChangeCost
    - Par_ProductionGrowthLimit
    - Par_RampingDownFactor
    - Par_RampingUpFactor
    - Par_ResidualStorageCapacity
    - Par_SelfSufficiency
    - Par_StorageLevelStart
    - Par_TechnologyFromStorage
    - Par_TechnologyToStorage
    - Par_TotalAnnualMinActivity
    - Par_TotalAnnualMinCapacity
    - Par_TradeLossFactor

#################################
  changed_files:
    - file_name: Par_RegionalModelPeriodEmissionLimit
      method: "copy"
      index_count: 2
      regions_to_split: 
        - 'NO'
      new_regions:  
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_ReserveMargin
      method: "copy"
      index_count: 2
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_GeneralDiscountRate
      method: "copy"
      index_count: 1
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_RegionalCCSLimit
      method: "copy"
      index_count: 1
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_ModalPeriodActivityMax
      method: "copy"
      index_count: 2
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_SocialDiscountRate
      method: "copy"
      index_count: 1
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TechnologyDiscountRate
      method: "copy"
      index_count: 2
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TotalAnnualMaxCapacity
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_AnnualExogenousEmission
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_BaseYearProduction
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_CapitalCost
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_REMinProductionTarget
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_ResidualCapacity
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TotalAnnualMaxActivity
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_EmissionPenalty
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_RegionalAnnualEmissionLimit
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0
         
    - file_name: Par_SpecifiedAnnualDemand
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_ComissionedTradeCapacity
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_GrowthRateTradeCapacity
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TradeCapacity
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TradeCapacityGrowthCosts
      method: "copy"
      index_count: 3
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_ModalSplitByFuel
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_OutputActivityRatio
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_RegionalBaseYearProduction
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_VariableCosts
      method: "copy"
      index_count: 4
      regions_to_split: 
        - 'NO'
      new_regions: 
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0
######################################
  trade_files:
    - file_name: Par_GrowthRateTradeCapacity
      method: "copy" 
      index_count: 2
      regions_to_split:
        - 'NO'
      new_regions:
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TradeRoute
      method: "copy" 
      index_count: 3
      regions_to_split:
        - 'NO'
      new_regions:
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TradeCapacity
      method: "copy" 
      index_count: 3
      regions_to_split:
        - 'NO'
      new_regions:
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

    - file_name: Par_TradeCapacityGrowthCosts
      method: "copy" 
      index_count: 3
      regions_to_split:
        - 'NO'
      new_regions:
        - 'NO1'
        - 'NO2'
      split_ratio: 
        'NO1': 1.0
        'NO2': 1.0

  time_series_files:
    - file_name: TS_COOL_LOW
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_HEAT_LOW
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_HEAT_HIGH
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_HP_AIRSOURCE
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_HP_GROUNDSOURCE
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_HYDRO_ROR
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_LOAD
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_MOBILITY_PSNG
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_PV_AVG
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_PV_INF
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_PV_OPT
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_PV_TRA
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_OFFSHORE
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_OFFSHORE_DEEP
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_OFFSHORE_SHALLOW
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_ONSHORE_AVG
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_ONSHORE_INF
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5

    - file_name: TS_WIND_ONSHORE_OPT
      regions_to_split:
          - 'NO'
      new_regions:
          - 'NO1'
          - 'NO2'
      split_ratio: 
          'NO1': 0.5
          'NO2': 0.5
########################################## new
  #special_files:
    #- file_name: Par_RegionalBaseYearProduction
      #index_count: 2
      #regions_to_split: 
        #- 'NO'
      #new_regions: 
        #- 'NO1'
        #- 'NO2'
      #split_factors:
        #Heat_District: {NO1: 0.5, NO2: 0.5} 
        #Heat_Low_Residential: {NO1: 0.3, NO2: 0.7} 
        #Heat_Low_Industrial: {NO1: 0.6, NO2: 0.4} 
        #Heat_Medium_Industrial: {NO1: 0.6, NO2: 0.4}
        #Heat_High_Industrial: {NO1: 0.6, NO2: 0.4}
        #Power: {NO1: 0.5, NO2: 0.5} #Area

    #- file_name: Par_BaseYearProduction
    #- file_name: Par_ModelPeriodExogenousEmission
    #- file_name: Par_ResidualCapacity
    #- file_name: Par_SpecifiedAnnualDemand


