no_change_parameters: 
    [Par_AnnualEmissionLimit,
    Sets,
    Par_AnnualSectoralEmissionLimit,
    Par_BaseYearSlack,
    Par_CapacityFactor,
    Par_CapitalCostStorage,
    Par_EmissionActivityRatio,
    Par_EmissionContentPerFuel,
    Par_FixedCost,
    Par_InputActivityRatio,
    Par_MinStorageCharge,
    Par_ModelPeriodEmissionLimit,
    Par_ModelPeriodExogenousEmission,
    Par_OperationalLife,
    Par_OperationalLifeStorage,
    Par_ProductionChangeCost,
    Par_ProductionGrowthLimit,
    Par_RampingDownFactor,
    Par_RampingUpFactor,
    Par_ResidualStorageCapacity,
    Par_SelfSufficiency,
    Par_StorageLevelStart,
    Par_TechnologyFromStorage,
    Par_TechnologyToStorage,
    Par_TotalAnnualMinActivity,
    Par_TotalAnnualMinCapacity,
    Par_TradeLossFactor]



changed_files:
    - file_name: Par_ReserveMargin
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_RegionalModelPeriodEmissionLimit
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_GeneralDiscountRate
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'
      
    - file_name: Par_RegionalCCSLimit
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_ModalPeriodActivityMax
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_SocialDiscountRate
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_TechnologyDiscountRate
      method: "sum"
      index_count: 2
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    # Indexed by 3

    - file_name: Par_TotalAnnualMaxCapacity
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_AnnualExogenousEmission
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_BaseYearProduction
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_CapitalCost
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_REMinProductionTarget
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_ResidualCapacity
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_TotalAnnualMaxActivity
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_EmissionPenalty
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'
    
    - file_name: Par_RegionalAnnualEmissionLimit
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_SpecifiedAnnualDemand
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_TradeCosts
      method: "sum"
      index_count: 3
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'


    #indexed by 4

    - file_name: Par_ComissionedTradeCapacity
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_GrowthRateTradeCapacity
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'      

    - file_name: Par_TradeCapacity
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_TradeCapacityGrowthCosts
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_TradeRoute
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_ModalSplitByFuel
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_OutputActivityRatio
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_RegionalBaseYearProduction
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

    - file_name: Par_VariableCosts
      method: "sum"
      index_count: 4
      regions_to_combine: 
        - 'NO'
        - 'SE'
      new_regions: 'SCANDINAVIA'

