blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/GENeSYS-MOD/GENeSYS_MOD.data/discussions
    about: Please use our GitHub Discussions page for questions and general ideas. :)