#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  5 14:37:23 2023

@author: shwetat
"""

sheet_no_mod = ['Par_TradeRoute',
             'Par_TradeCosts',
             'Par_TradeCapacity',
             'Par_TradeCapacityGrowthCosts',
             'Par_GrowthRateTradeCapacity',
             'Par_RegionalAnnualEmissionLimit',
             'Par_EmissionsPenalty',
             'Par_SpecifiedAnnualDemand',
             'Par_ReserveMargin',
             'Par_ResidualCapacity',
             'Par_AvailabilityFactor',
             'Par_TotalAnnualMaxActivity',
             'Par_TotalAnnualMaxCapacity',
             'Par_ModelPeriodActivityMaxLimit',
             'Par_RegionalCCSLimit',
             'Par_RegionalBaseYearProduction',
             'Par_ModalSplitByFuel',
             'Sets',
             'Par_DaySplit',
             'Par_YearSplit',
             'Par_TagTechnologyToSector',
             'Par_CapacityToActivityUnit',
             'Par_Conversionls',
             'Par_Conversionld',
             'Par_Conversionlh',
             'Par_AnnualExogenousEmission',
             'Par_AnnualEmissionLimit',
             'Par_AnnualSectoralEmissionLimit',
             'Par_EmissionActivityRatio',
             'Par_EmissionPenaltyTagTech',
             'Par_EmissionContentPerFuel',
             'Par_ReserveMarginTagFuel',
             'Par_ReserveMarginTagTechnology',
             'Par_InputActivityRatio',
             'Par_OutputActivityRatio',
             'Par_CapitalCost',
             'Par_VariableCost',
             'Par_FixedCost',
             'Par_CapacityFactor',
             'Par_OperationalLife',
             'Par_TotalAnnualMinActivity',
             'Par_TotalAnnualMinCapacity',
             'Par_TagTechnologyToModalType',
             'Par_BaseYearProduction',
             'Par_TechnologyToStorage',
             'Par_TechnologyFromStorage',
             'Par_StorageLevelStart',
             'Par_StorageMaxChargeRate',
             'Par_StorageMaxDischargeRate',
             'Par_MinStorageCharge',
             'Par_OperationalLifeStorage',
             'Par_CapitalCostStorage',
             'Par_ResidualStorageCapacity']
