name: MiddleEarth Release Excel

on:
  release:
    types: [published]   # run when a release is published

permissions:
  contents: write  # needed to upload assets to the release

jobs:
  build-xlsx:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "Conversion Script/requirements.txt" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run MiddleEarth conversion script
        run: |
          python "Conversion Script/script_middleearth.py"

      - name: Upload Excel to release
        uses: softprops/action-gh-release@v2
        with:
          files: Output/output_excel/RegularParametersMiddleEarth.xlsx
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
